### ISSUE TITLE
Add a "Are you sure" part to the SellingPage wizard

### ISSUE THREAD

**Issue by Danryg** [emilsvennesson/dat257-xzibit#25]
A thought is to add a "are you sure part" to the selling page wizard with an Ad card or small component that shows how the ad will look right before publishing

**Comment by Kexon** [comment]
Elaborate why adding a "are you sure part" would benefit the selling page wizard. (Not against the idea, but explaining your thoughts might help your point).

**Comment by Danryg** [comment]
This will not be implemented
