### ISSUE TITLE
Searching with queries that returns a lot of books

### ISSUE THREAD

**Issue by EliasFalk** [emilsvennesson/dat257-xzibit#28]
Hello guys, there is an issue where searching for "ste" then continuing to "stefan".
The query for retrieving the books for "ste" is much longer than the time it takes to return the books by "stefan" and results in the books from "ste" overriding the books from "stefan" in the search field.
This is because the function that searches for and returns the books is asynchronous and allows for both of the search "ste" and "stefan" to run simultaneously. This means that the longer query will the be one that will be shown in the end.

Please fix.

**Comment by Kexon** [comment]
Is there any way to cancel queries? If so when typing a word, you'd cancel all current coroutines before issuing a new query.

**Comment by EliasFalk** [comment]
@Danryg came with a fix which sort of solves the problem but it will not abort any queries. See 4cfd7fd26e33365b6f111a83b28549be3376deb6. 
So the underlying problem is still there but the user will not notice anything and the search works as intended for the user.
